name: custom-env
channels:
  - defaults
dependencies:
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.10.16
  - certifi=2019.9.11
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - importlib_metadata=0.23
  - intel-openmp=2019.4
  - ipykernel=5.1.3
  - ipython=7.9.0
  - ipython_genutils=0.2.0
  - jedi=0.15.1
  - jinja2=2.10.3
  - jsonschema=3.2.0
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - libffi=3.2.1
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=7.2.0
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - notebook=6.0.2
  - numpy=1.17.4
  - openssl=1.1.1d
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.3.1
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - pygments=2.4.2
  - pyrsistent=0.15.6
  - python=3.7.5
  - python-dateutil=2.8.1
  - pyzmq=18.1.0
  - send2trash=1.5.0
  - setuptools=42.0.1
  - six=1.13.0
  - sqlite=3.30.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
      - nengo==2.8.0
      - nengo-gui==0.4.5
